name: ecommerce_flutter
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  rxdart: ^0.28.0
  fluttertoast: ^9.0.0
  http: ^1.5.0
  get_it: ^9.0.5
  injectable: ^2.6.0
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  bloc: ^9.1.0
  image_picker: ^1.2.1
  path: ^1.9.1
  http_parser: ^4.1.2
  app_links: ^7.0.0
  pinput: ^6.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.9.1
  build_runner: ^2.10.1

flutter:
  uses-material-design: true
  assets:
    - assets/img/

